# Generated by Django 3.1.3 on 2020-11-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
